version: "3.9"

services:
  myfront:
    build: ./myfront
    networks:
      - cloud-native
    ports:
      - "3000:3000"
    volumes:
      - ./myfront:/app
      - /app/node_modules
    depends_on:
      - myuserapi
      - mylinkapi
    environment:
      - CHOKIDAR_USEPOLLING=true

  myuserapi:
    build: ./myuserapi
    networks:
      - cloud-native
    ports:
      - "8001:8001"
    volumes:
      - ./myuserapi:/app
      - /app/node_modules
    depends_on:
      - db
    environment:
      - DB_HOST=mysql
      - DB_USER=mysql_db
      - DB_PASSWORD=123456
      - DB_NAME=mysql_db

  mylinkapi:
    build: ./mylinkapi
    networks:
      - cloud-native
    ports:
      - "8002:8002"
    volumes:
      - ./mylinkapi:/app
      - /app/node_modules
    depends_on:
      - db
    environment:
      - DB_HOST=mysql
      - DB_USER=mysql_db
      - DB_PASSWORD=123456
      - DB_NAME=mysql_db

  db:
    image: mysql:8
    container_name: mysql
    networks:
      - cloud-native
    ports:
      - "33306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: mysql_db
      MYSQL_USER: mysql_db
      MYSQL_PASSWORD: 123456
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - db_data:/var/lib/mysql

networks:
  cloud-native:
    driver: bridge

volumes:
  db_data:
