version: "3.9"

services:
  myfront:
    build: ./myfront
    networks:
      - mynet
    ports:
      - "3000:3000"
    volumes:
      - ./myfront:/app
      - /app/node_modules
    depends_on:
      - myuserapi
      - mylinkapi
    environment:
      - CHOKIDAR_USEPOLLING=true

  myuserapi:
    build: ./myuserapi
    networks:
      - mynet
    ports:
      - "8001:8001"
    volumes:
      - ./myuserapi:/app
      - /app/node_modules
    depends_on:
      - db
      - myredis
    environment:
      - DB_HOST=mysql
      - DB_USER=mysql_db
      - DB_PASSWORD=123456
      - DB_NAME=mysql_db
      - REDIS_HOST=myredis
      - REDIS_PORT=6379

  mylinkapi:
    build: ./mylinkapi
    networks:
      - mynet
    ports:
      - "8002:8002"
    volumes:
      - ./mylinkapi:/app
      - ./uploads:/app/uploads
      - /app/node_modules
    depends_on:
      - db
      - myredis
    environment:
      - PUBLIC_URL=http://insightbox.com
      - DB_HOST=mysql
      - DB_USER=mysql_db
      - DB_PASSWORD=123456
      - DB_NAME=mysql_db
      - REDIS_HOST=myredis
      - REDIS_PORT=6379

  db:
    image: mysql:8
    container_name: mysql
    networks:
      - mynet
    ports:
      - "33306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: mysql_db
      MYSQL_USER: mysql_db
      MYSQL_PASSWORD: 123456
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - db_data:/var/lib/mysql

  myredis:
    image: redis:7
    container_name: myredis
    networks:
      - mynet
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  nginx:
    image: nginx:latest
    container_name: myproxy
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./uploads:/usr/share/nginx/html/uploads
    depends_on:
      - myfront
      - myuserapi
      - mylinkapi
    networks:
      - mynet

networks:
  mynet:
    driver: bridge

volumes:
  db_data:
  redis_data:
